version: "3"

services:
  backend:
    build: .
    container_name: triple_backend
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: on-failure:10
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://triple_mysql:3306/triple?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - triple_network

  database:
    image: mysql:8.0.26
    container_name: triple_mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=triple
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - triple_network

networks:
  triple_network: